# Generated by Django 4.2.7 on 2023-11-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSucursal', models.CharField(max_length=70)),
                ('Direccion', models.CharField(max_length=80)),
                ('HorarioAbierto', models.TimeField()),
                ('HorarioCerrado', models.TimeField()),
                ('Telefono', models.FloatField(max_length=10)),
                ('Correo', models.CharField(max_length=70)),
            ],
        ),
    ]
