# Generated by Django 4.2.7 on 2023-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sucursales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctores',
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='Telefono',
            field=models.IntegerField(),
        ),
    ]
